login/urls.py
'''
Created on Sep 15, 2013

@author: steven
'''
from django.conf.urls import patterns, url
from views import link_index, register, create_user, authorize, logout_view


urlpatterns = patterns ('',
    url('^$', link_index, name='index'),
    url(r'^(?i)register/', register),
    url(r'^(?i)createuser/', create_user),
    url(r'^(?i)authenticate/', authorize),
    url(r'^(?i)logout/', logout_view, name='logout'),
)

luminary/urls.py
from django.conf.urls import patterns, include, url
from luminary.views import home, \
    create_assignments, \
    add_assignment, \
    create_assignment, \
    user_details, \
    users_list, \
    view_assignment_list, \
    view_assignment, \
    introduction, \
    critical_thinking, \
    question_bank, \
    lectures, \
    add_question, \
    question_list, \
    delete_answer_from_question, \
    add_answers_to_question, \
    update_question, \
    update_answer, \
    answer_questions, \
    submit_answers

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
                       url(regex=r'^$', view=home, name='home_url'),
                       url(regex=r'^(?i)login/', view=include('login.urls'), name='login_url'),
                       url(r'^(?i)assignments/', view_assignment_list),
                       url(r'^(?i)assignments/(\d+)/', view_assignment),
                       url(r'^(?i)create_assignments/', create_assignments),
                       url(r'^(?i)create_assignment/(\d+)/', create_assignment),
                       url(r'^(?i)lectures/(?P<value>\d+\.\d{2})/$', lectures),
                       url(r'^(?i)add_assignment/', add_assignment),
                       url(r'^(?i)question_bank/', question_bank),
                       url(r'^(?i)users/', users_list),
                       url(r'^(?i)user/(\d+)/', user_details),
                       url(r'^(?i)Introduction/', introduction),
                       url(r'^(?i)critical_thinking/', critical_thinking),
                       url(r'^(?i)Question/', add_question),
                       url(r'^(?i)QuestionList/', question_list),
                       url(r'^(?i)DeleteAnswer/', delete_answer_from_question),
                       url(r'^(?i)UpdateQuestion/', update_question),
                       url(r'^(?i)UpdateAnswer/', update_answer),
                       url(r'^(?i)AddAnswersToQuestion/', add_answers_to_question),

                       url(r'^(?i)lectures/question-example/', answer_questions),
                       url(r'^(?i)lectures/submit-question/', submit_answers),
)

luminary/models.py
from django.db import models
# Matt's test models


class OperationalDefinitions(models.Model):
    # student = models.ForeignKey(Questions)
    question1 = models.TextField(null=False)
    question2 = models.TextField(null=False)
    question3 = models.TextField(null=False)

# Create your models here.


class Questions(models.Model):
    question = models.TextField(null=False)
    image = models.ImageField()
    MC = 'Multiple Choice'
    WORD = 'Word'
    DECIMAL = 'Decimal'
    TYPE = (
        (MC, 'Multiple Choice'),
        (WORD, 'Word'),
        (DECIMAL, 'Decimal'),
    )
    type = models.CharField(max_length=15,
                            choices=TYPE,
                            default=MC)


class Answers(models.Model):
    answer = models.TextField(null=False)
    question = models.ForeignKey(Questions)
    correct = models.BooleanField(default=True)
    image = models.ImageField()


class QuestionTags(models.Model):
    question = models.ForeignKey(Questions)
    tag = models.TextField(max_length=40)


class Assignments(models.Model):
    due_date = models.DateTimeField()
    point_value = models.DecimalField(null=False, max_digits=3, decimal_places=2)
    title = models.TextField(max_length=50)
    TEST = 'Test'
    HOMEWORK = 'HOMEWORK'
    TYPE = (
        (TEST, 'Test'),
        (HOMEWORK, 'Homework'),
    )
    type = models.CharField(max_length=8,
                            choices=TYPE,
                            default=HOMEWORK)


class AssignmentQuestions(models.Model):
    assignment = models.ForeignKey(Assignments)
    question = models.ForeignKey(Questions)


class Students(models.Model):
    student_first_name = models.TextField()
    student_last_name = models.TextField()
    student_id = models.IntegerField()


class StudentQuestionsPassed(models.Model):
    student = models.ForeignKey(Students)
    question = models.ForeignKey(Questions)
    passed = models.BooleanField(default=False)


class Grades(models.Model):
    grade = models.DecimalField(max_digits=3, decimal_places=2)
    student = models.ForeignKey("Students")
    assignment = models.ForeignKey("Assignments")

luminary/views.py
from json import dumps, loads
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.views.decorators.csrf import ensure_csrf_cookie
from models import Questions, Assignments, QuestionTags, Answers
from forms import QuestionForm, AssignmentForm, QuestionTagsFormSet, QuestionTagsForm, AdminForm, UserForm, NameForm
from django.http import JsonResponse
from django.core.context_processors import csrf #in django 1.8 this is moved to django.templates.context_processors

title = "Luminary Academy"


def home(request):
    dictionary = request.session
    dictionary['title'] = title
    dictionary['first_name'] = __get_session(request)
    return render(request, 'luminary/templates/menu.html', dictionary)


def introduction(request):
    dictionary = request.session
    dictionary['title'] = title
    dictionary['first_name'] = __get_session(request)
    return render(request, 'luminary/templates/Introduction.html', dictionary)


def critical_thinking(request):
    dictionary = request.session
    dictionary['title'] = title
    dictionary['first_name'] = __get_session(request)
    return render(request, 'luminary/templates/Critical_Thinking.html', dictionary)


def create_assignments(request):
    dictionary = {'title': title, 'assignments': _load_assignments, 'form': AssignmentForm,
                  'first_name': __get_session(request)}
    return render(request, 'luminary/templates/create-assignments.html', dictionary)

@ensure_csrf_cookie
def question_bank(request):
    dictionary = {'title': title, 'assignments': _load_assignments, 'first_name': __get_session(request),
                  'tags_form': QuestionTagsForm()}
    dictionary.update(csrf(request))
    return render(request, 'luminary/templates/questions/questionBank.html', dictionary)


def add_assignment(request):
    if request.method == "POST":
        form = AssignmentForm(request.POST)
        if form.is_valid():
            Assignments.objects.create(due_date=form.cleaned_data['due_date'],
                                       point_value=form.cleaned_data['point_value'],
                                       title=form.cleaned_data['title'],
                                       type=form.cleaned_data['type'], )
        else:
            raise Http404
    return HttpResponse(dumps(_load_assignments()), content_type="application/json")


def view_assignment_list(request):
    assignments = Assignments.objects.all()
    dictionary = {'title': title, 'assignments': assignments}
    return render(request, 'luminary/templates/assignment_list.html', dictionary)


def view_assignment(request):
    dictionary = {}
    return render(request, 'luminary/templates/assignments.html', dictionary)


def _load_assignments():
    assignment_dict = {}
    for assignment in Assignments.objects.all():
        assignment_dict[assignment.title] = assignment.id
    return assignment_dict


def create_assignment(request, num=None):
    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        current_assignment = Assignments.objects.get(pk=num)
        if question_form.is_valid():
            question = Questions.objects.create(question=question_form.cleaned_data['question'],
                                                answer=question_form.cleaned_data['answer'],
                                                point_value=question_form.cleaned_data['point_value'],
                                                assignment=current_assignment, )
            tags_inline_formset = QuestionTagsFormSet(request.POST, request.FILES, instance=question, )
            if tags_inline_formset.is_valid():
                for Tags in tags_inline_formset:
                    for tag in Tags.cleaned_data['tag'].split(","):
                        question_tag = QuestionTags.objects.create(question=question,
                                                                   tag=tag, )
                        question_tag.save()

    try:
        assignment_name = Assignments.objects.get(pk=num).title
    except Assignments.DoesNotExist:
        assignment_name = None

    question_list = []
    try:
        question_list = _load_questions(num)

    except Questions.DoesNotExist:
        pass

    dictionary = {'title': title, 'assignment': num, "assignment_name": assignment_name, "questions": question_list,
                  'formset': QuestionTagsFormSet, 'form': QuestionForm, 'first_name': __get_session(request)}
    return render(request, 'luminary/templates/create-assignment.html', dictionary)


def user_details(request, user_id=None):
    __check_permissions('staff', request.user)
    if request.method == "POST":
        in_form = AdminForm(request.POST)
        if in_form.is_valid():
            User.objects.filter(pk=user_id).update(email=in_form.cleaned_data['email'],
                                                   username=in_form.cleaned_data['email'],
                                                   is_staff=in_form.cleaned_data['is_staff'], )
    current_user = User.objects.get(pk=user_id)
    out_form = AdminForm(initial={'email': current_user.email, 'is_staff': current_user.is_staff})
    dictionary = {'title': title, 'form': out_form, 'first_name': __get_session(request)}
    return render(request, 'luminary/templates/user.html', dictionary)


def users_list(request):
    __check_permissions('staff', request.user)
    users = User.objects.all()
    all_users = []
    form = UserForm()
    for current_user in users:
        all_users.append(current_user)
    dictionary = {'users': all_users, 'title': title, 'form': form, 'first_name': __get_session(request)}
    return render(request, 'luminary/templates/users.html', dictionary)


def __get_session(request):
    first_name = None
    try:
        email = request.session['email']
        first_name = User.objects.get(email=email).first_name
    except AttributeError:
        pass
    except KeyError:
        pass
    return first_name


def _load_questions(assignment_id):
    questions = []
    for question in Questions.objects.filter(assignment_id=assignment_id):
        questions.append([question.question, question.answer, question.point_value, ]),
    return questions


def __get_user_permissions(user_to_validate):
    permissions = "user"
    if user_to_validate.is_superuser:
        permissions = "superuser"
    elif user_to_validate.is_staff:
        permissions = "staff"
    return permissions


def __check_permissions(required_permissions, user_to_validate):
    permission = __get_user_permissions(user_to_validate)
    if required_permissions == "superuser":
        if permission in "superuser":
            pass
        else:
            raise PermissionDenied
    elif required_permissions == "staff":
        if permission in ('superuser', 'staff'):
            pass
        else:
            raise PermissionDenied
    else:
        pass


def lectures(request, num=None):
    dictionary = request.session
    dictionary['title'] = title
    dictionary['first_name'] = __get_session(request)
    url = 'luminary/templates/lectures/' + num + '.html'
    #the following block is matt practicing with forms
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()
    return render(request, url, {'form': form})


def add_question(request):
    data = {
        'b': 3,
    }
    return JsonResponse(data)


def question_list(request):
    data = []
    for question in Questions.objects.all():
        answers = []
        try:
            for answer in Answers.objects.filter(question=question):
                answer_info = {
                    "answer": answer.answer,
                    "correct": answer.correct,
                    "id": answer.id,
                }
                answers.append(answer_info)
        except ObjectDoesNotExist:
            pass

        row = {
            "id": question.id,
            "question": question.question,
            "answers": answers,
        }
        data.append(row)
    return HttpResponse(dumps(data))


def delete_answer_from_question(request):
    if request.method == "DELETE":
        answer = loads(request.GET['answer'])
        Answers.objects.get(pk=answer['id']).delete()


def add_answers_to_question(request):
    if request.method == "POST":
        answer = loads(request.body)['params']['answer']
        question = loads(request.body)['params']['question']
        db_answers = Answers.objects.create(answer=answer, question_id=int(question['id']))
        db_answers.save()
        return HttpResponse(db_answers.id)


def update_answer(request):
    if request.method == "POST":
        answer = loads(request.body)['params']['answer']
        question = loads(request.body)['params']['question']
        db_answers = Answers.objects.create(answer=answer, question_id=int(question['id']))
        db_answers.save()
        return HttpResponse(db_answers.id)


def update_question(request):
    # __check_permissions('staff', request.user)
    if request.method == "POST":
        question_dictionary = loads(request.body)
        question = question_dictionary['question']
        answers = question_dictionary['answers']
        question_type = "Multiple Choice" if len(answers) > 1 else "Word"
        if question_dictionary['id'] == "":
            new_question = Questions.objects.create(question=question, type=question_type)
            new_question.save()

luminary/templates/AnswerQuestions.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block stylesheets %}
    <link href="../../static/css/signin.css" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container">
	<form class="form-questions" method="post" action="{% block form_action %}{% endblock%}">{% csrf_token %}
	    {% block fields %}
	    <h2 class="form-signin-heading">Add A Question</h2>
	    {{ form.non_field_errors }}
	    <div class="row">
            <div class="fieldWrapper col-lg-6">
                {{ form.question.errors }}
                {{ form.question }}
            </div>
            <div class="fieldWrapper col-lg-6">
                {{ form.answer.errors }}
                {{ form.answer }}
            </div>
	    </div>
        <div class="fieldWrapper col-lg-2">
	        {{ form.point_value.errors }}
	        {{ form.point_value }}
	    </div>
	    <div class="fieldWrapper col-lg-2">
	        {{ form.chapter.errors }}
	        {{ form.chapter }}
	    </div>
	    {% endblock %}

	    <div class="row" style="padding-top: 40px">
            <div class="col-lg-3">
                <button class="btn btn-lg btn-primary btn-block" type="submit">{% block login %}Add Question {% endblock %}</button>
            </div>
        </div>
	</form>
    </div>
{% endblock%}

luminary/templates/Creative_Thinking.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block content %}

Outline:
-Define Creative Thinking
	-Think of new stuff
	-Also simply create. i.e. create new models, ways of representing physics
-Why creative thinking
-Goals of creative thinking


{% endblock %}

luminary/templates/Critical_Thinking.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block content %}

Outline:
-The challenge to become - a critical thinker, and thereby a better person
-Define Critical Thinking
-Why critical thinking
	-How many physics papers are published a day? year?  How can we learn 'everything' with so much knowledge
	 being added to the world everyday
	-That is physics knowledge, but what about other knowledge needed to be a good citizen and its connection
	 to physics?
-Goals of critical thinking
	-Be able to transfer skills from one domain/subject to another
	-Analyze problems in rigorous way
	-Make decisions
-Bloom's Taxonomy of thinking types
	-Be aware of different types of learning/thinking/mastery
	-Just having physics knowledge is not particularly useful
		-Why?
	-Having different skills of thinking like different tools in toolbox, not
	 so important if one is more useful or not than the other, all are useful
	 in certain contexts.


Being a critical thinker is not the same as being smart, and anyone can do it.

Goals of Critical Thinking


Some notes about critical thinking
From Greek kritikos - to descern, from kreinein, to judge decide 
critical thinking is about making informed descisions.  Thus, very similar to scientific method.  About
taking all available data/information and make the best possible decisions.


{% endblock %}

luminary/templates/Introduction.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block content %}

This is a test page for the moment.
$a=\frac{v^2}{r}$

Physics underlies everything.
{% endblock %}

luminary/templates/ScientificMethod.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block content %}

The scientific method is too often presented as a set of steps like a 
recipe.  Science and the methods are more involved, like artwork.  Just as in painting,
there are certain steps and techniques that work better say in painting. 

Loosely speaking, Aristotle thought reason could lead to all truth, 
starting with Galileo experiment became more important.
{% endblock %}

luminary/templates/assignment_list.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block content %}
    <form class="form-user" method="POST" action="">{% csrf_token %}
        <table>
        {% for assignment in assignments %}
            <h1>Question List</h1>
        {% endfor %}
        </table>
    </form>
{% endblock %}

luminary/templates/assignments.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block content %}
    <form class="form-user" method="POST" action="">{% csrf_token %}

    </form>
{% endblock %}

luminary/templates/chapters.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <div class="span10 offset1">
                Vector
            </div>
        </div>
    </div>

{% endblock %}

luminary/templates/create-assignment.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block stylesheets %}
    <link href="../../static/css/signin.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
	    {% block fields %}
	    <h2 class="heading">{{ assignment_name }}</h2>
	    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addQuestionModal">+ Question</button>

        <table id="question-table">
            <thead>
                <tr>
                    <th>Question</th>
                    <th>Answer</th>
                    <th>Point Value</th>
                </tr>
            </thead>
            <tbody>
                {% for question, answer, point_value in questions %}
                    <tr>
                        <td>{{ question }}</td>
                        <td>{{ answer }}</td>
                        <td>{{ point_value }}</td>
                    </tr>
                {% endfor %}
            </tbody>
	    </table>

        <div class="modal fade" id="addQuestionModal" tabindex="-1" role="dialog" aria-labelledby="addQuestionModalLabel" aria-hidden="true">
            <form class="form-questions" method="post" action="{% block form_action %}{% endblock %}">{% csrf_token %}
                <input type="hidden" value="{{ num }}" id="assignment"/>
                <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="addQuestionModalLabel">Add A Question</h4>
                  </div>
                  <div class="modal-body">

                      <div class="container">
                            <table>
                                {{ form.as_table }}
                                {{ formset.as_table }}
                            </table>

                      </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button id="add-question"  type="submit" class="btn btn-primary">Save</button>
                  </div>
                </div>
              </div>
            </form>
        </div>
        {% endblock %}
    </div>
{% endblock%}

{% block jslibraries %}
    <script>
        $(document).ready(function() {
            $('#question-table').dataTable();
        });
    </script>
{% endblock %}

luminary/templates/create-assignments.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block stylesheets %}
    <link href="../../static/css/signin.css" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container">
	    {% block fields %}
	    <h2 class="heading">Assignments</h2>
	    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addAssignmentModal">+ Assignment</button>

        <ul id="assignment-list">
            {% for key, value in assignments.items %}
                <li><a href="{% url 'views.create_assignment' value %}">{{ key }}</a></li>
            {% endfor %}
	    </ul>

        <div class="modal fade" id="addAssignmentModal" tabindex="-1" role="dialog" aria-labelledby="addAssignmentModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="addAssignmentModalLabel">Add An Assignment</h4>
              </div>
              <form id="add_assignment_form" class="cmxform" method="POST">
              <div class="modal-body">
                      <fieldset>
                      <div class="row">
                            <div class="fieldWrapper col-lg-6">
                                {% csrf_token %}
                                {{ form.title.errors }}
                                {{ form.title }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="fieldWrapper col-lg-6">
                                {{ form.point_value.errors }}
                                {{ form.point_value }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="fieldWrapper col-lg-6">
                              {{ form.due_date.errors }}
                              <div id="due_datetimepicker" class="input-group date">
                                {{ form.due_date }}
                                <span class="input-group-addon glyphicon glyphicon-calendar"></span>
                              </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="fieldWrapper col-lg-6">
                                {{ form.type.errors }}
                                {{ form.type }}
                            </div>
                        </div>
                        </fieldset>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" id="add-assignment" class="btn btn-primary">Save</button>
              </div>
              </form>
            </div>
          </div>
        </div>

        {% endblock %}
    </div>
{% endblock%}

{% block jslibraries %}
    <script>
        $(function() {
            debugger;
            $('#add_assignment_form').bootstrapValidator({
                excluded: [':disabled'],
                message: 'This value is not valid',
                feedbackIcons: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    due_date: {
                        validators: {
                            notEmpty: {
                                message: 'A valid due date is required'
                            }
                        }
                    },
                    title: {
                        validators: {
                            notEmpty: {
                                message: 'An assignment name is required'
                            }
                        }
                    },
                    point_value: {
                        validators: {
                            notEmpty: {
                                message: 'The point value is required'
                            }
                        }
                    }
                },
                submitButtons: 'button[id=add-assignment]',
                submitHandler: function(validator, form, submitButton) {
                    debugger;
                    var hours = new Date($('#id_due_date').val()).getHours();
                    var minutes = new Date($('#id_due_date').val()).getMinutes();
                    var dateArray = $('#id_due_date').val().split(" ");
                    var date = dateArray[0] + " " + hours + ":" + minutes;
                    $.ajax({
                        type: "POST",
                        url: {% url 'views.add_assignment' %},
                        data: { 'due_date': date,
                                'point_value': $('#id_point_value').val(),
                                'title': $("#id_title").val(),
                                'type':$('#id_type').val() }
                    }).success(function(assignments){
                        alert("test");
                       var assignmentArray = [];
                       for(var key in assignments) {
                           var url = "{% url 'views.create_assignment' 1 %}";
                           var urlArray = url.split("/");
                           var cleanArray = [];
                           url = "";
                           var count = 0;
                           for(var i=0; i < urlArray.length; i++)
                           {
                               if(urlArray[i] != "") {
                                    cleanArray[count++] =  urlArray[i];
                               }
                           }
                           for(var j=0;j<cleanArray.length - 1;j++) {
                               url += "/" + cleanArray[j];
                           }
                        assignmentArray.push("<li><a href=\"" + url + "/" + assignments[key] +" \">" + key +  "</a></li>");
                       }
                        $("#assignment-list").empty();
                        $("#assignment-list").append(assignmentArray.join(''));
                        $("#addAssignmentModal").modal('hide');
                    }).fail( function(request, status, error){ });
                    return false;
                }
            });

            $('#due_datetimepicker').datetimepicker({
                language: 'en',
                pick12HourFormat: true
            });
      });
    </script>
{% endblock %}

luminary/templates/menu.html
{% extends "luminary/templates/LuminaryMenu.html" %}
{% block stylesheets %}
    <link href="{{ STATIC_URL }}css/carousel.css" rel="stylesheet">
{% endblock %}


{% block content %}
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class=""></li>
        <li class="active" data-target="#myCarousel" data-slide-to="1"></li>
        <li class="" data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item">
          <img src="{{ STATIC_URL }}images/heic1302a.jpg">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code>
 URL, the "next" and "previous" Glyphicon buttons on the left and right
might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item active">
          <img src="{{ STATIC_URL }}images/fiber-optic.JPG" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget
quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor
id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="{{ STATIC_URL }}images/Acadia.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget
quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor
id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->
{% endblock %}